import Head from "next/head";
import Benefits from "../components/Benefits";
import Details from "../components/Details";
import Feedback from "../components/Feedback";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Locations from "../components/Location";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>InDecor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="stylesheet" href="css/styles.css" />
        {/* Text font */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main>
        <Header />
        <Benefits />
        <Locations />
        <Details />
        <Feedback />
        <Footer />
      </main>
    </div>
  );
}
